### ISSUE TITLE
Support nested gramGrp

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#100]
For possessives with multiple person/gender (e.g. ⲧⲉϥ). Example:

```
<gramGrp>
<gramGrp>Possessum</gramGrp>
<gramGrp>Possessor</gramGrp>
</gramGrp>
```

**Comment by phoenix-mossimo** [comment]
See also https://github.com/DARIAH-ERIC/lexicalresources/issues/78

**Comment by phoenix-mossimo** [comment]
I removed nested <GramGrp> because they also created inconsistency with the  TLA data model where "one lemma" = "one pos value". The solution for CCL V 1.2 is to relegate the possessor information to the `<def>` tag in `<sense>`, e.g.: 

```
<cit type="translation" xml:lang="de">
<quote>dein(e)</quote>
<def>Possessivartikel; [possessed]: m. sg., [possessor]: 2 p. f. sg. </def>
</cit>
<cit type="translation" xml:lang="en">
<quote>your</quote>
<def>possessive article; [possessed]: m. sg., [possessor]: 2 p. f. sg. </def>
</cit>
<cit type="translation" xml:lang="fr">
<quote>ton, ta</quote>
<def>article possessif; [possessed]: m. sg., [possessor]: 2 p. f. sg. </def>
</cit>
```
With the next version we will encode all grammatical information inline with LEX-0, using `<gram type="gram_category">` tags. This will allow to disambiguate the possessor and possessum info for example as follows: 

```
ⲡⲁ- C2784
<gram type="gen">m.</gram>
<gram type="number">sg.</gram>
<gram type="person[psor]">1.</gram>
<gram type="number[psor]">sg.</gram>
```
For the description of the problem and the suggested solutions, see: https://github.com/KELLIA/dictionary/wiki/Encoding-the-possessor-&-possessed-information-with-possessive-pronouns,-articles-and-prefixes

This issue is closed.
