### ISSUE TITLE
Inconsistency in the ⲛⲧⲉ- forms

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#111]
1)

https://coptic-dictionary.org/entry.cgi?tla=C2532

  | (En) | indicating possession, ownership
  | (Fr) | chez, avec
  | (De) | bei, im Besitz von, zusammen mit

Explanation in English, translation in French and German

2)

https://coptic-dictionary.org/entry.cgi?tla=C2533

(En) | paticle of genitive

Typo

3)

At points the CD explains lemmas, at points it translates them, and sometimes it's a mix like right here

**Comment by phoenix-mossimo** [comment]
> 1. Explanation in English, translation in French and German

Extended English as follows 

```
            <cit type="translation" xml:lang="en">
              <quote>(together) with, at [indicating possession, ownership]</quote>
            </cit>
```

> 2. Typo 

Corrected as follows

```<quote>paticle of genitive</quote>``` -> ```<quote>particle of genitive</quote>```

> 3. At points the CD explains lemmas, at points it translates them, and sometimes it's a mix like right here

Yes, it can be at times inconsistent, conditioned by : 

- the use of different dictionaries. In the above (1) example Crum (our main source), does not give the translation, all other dictionaries do. 

- Another reason are the Gram Grp (TEI XML) encoding constrains: e.g. in  #112 I had to put some of the grammatical information into the translation in squared brackets `<quote>if [verbal prefix of the conditional]</quote>`, because the Gram Grp tags were occupied already: 

```
          <gramGrp>
            <pos>Verbalpräfix</pos>
            <subc>Status nominalis</subc>
          </gramGrp>
```
