### ISSUE TITLE
Sort forms

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#114]
Currently the display of the forms is a bit of a mess, e.g.

https://coptic-dictionary.org/entry.cgi?tla=C616

Forms should be sorted according to the dialects in the alphabetical order, with the exception of "form type=lemma", which should keep the first position.

**Comment by amir-zeldes** [comment]
I think they're currently in the XML file order, which often places Sahidic at the top. Don't we want Sahidic to be at the top as the reference form though? Also, I think it looks less jarring if the forms are alphabetized before dialects, otherwise the entry linked above would have a constant switch between:

e-
ere
e=
e-
ere
e=
...

For all the dialects, which I think would look worse than right now...

**Comment by phoenix-mossimo** [comment]
Hm, maybe you are right, sorting according to the spelling also makes sense. Let's see how it looks on the test-server, once you upload it.

**Comment by amir-zeldes** [comment]
The latest version is deployed in dev now, let me know if we should close this.

**Comment by phoenix-mossimo** [comment]
Hm, the test-server does not show the latest V1.5_Beta.xml, the forms are not sorted properly. Are you sure you uploaded the latest file?

https://corpling.uis.georgetown.edu/coptic-dictionary-dev/entry.cgi?tla=C616

**Comment by amir-zeldes** [comment]
Yes, it is the right file, but you are correct that the order is different. I've looked into this now and it's a little bit complex:

  * Lemma forms can be duplicates of entries without type="lemma"
  * At some point we made a sensible decision that we want the lemma form to be first
  * If there is a duplicate, we place only one copy of the lemma at the top, BUT, there can be many forms identical to the lemma (e.g. in different dialects, or because two inflectional paradigm forms happen to be identical, i.e. syncretic)

Because of these constraints, the ordering algorithm is currently:

  * Collect all forms and filter for duplicate lemma entry in XML
  * Place all forms identical to the lemma first, in the order in which they appear in XML
  * Place all remaining forms afterwards, also in the order in which they appear in XML

In the case you pointed out, this looks not so great, but I'm not sure if/how we want to change this, since the constraint that forms identical to the lemma should appear first does make some sense.

Maybe we just want to sort the block of non-lemma forms differently? Alphabetically? By dialect? Or should we just 100% follow XML order and give up the 'lemma form first' constraint? 

Let me know what you think!

**Comment by phoenix-mossimo** [comment]
I did not know you sort the forms. Now that you say that you place forms identical to the lemma first - I think this is reasonable. This basically presupposes that the rest of the list should be organized according to forms.  How about extending this criterion with a dialect sorting? I.e.: 

1) Put all forms identical to lemma first AND sort them according to dialects: A, B, etc. 
2) Sort the rest of the forms in the alphabetical order AND sort identical forms within this list according to the dialects. 

If it is too complex to do on your side, I can try this within XML itself, but probably not in the current release (V1.2) we are preparing.

**Comment by amir-zeldes** [comment]
No, that shouldn't be too difficult. But do we really want to sort Akhmimic first and not Sahidic? Looking at Crum, when there are multiple dialects he seems to follow SABF, for example for ti:

http://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=392

Let me know what dialect order you think would be best and I can implement this.

**Comment by phoenix-mossimo** [comment]
True, OK then S first and then alphabetic. Would be nice to have the specification of this and other features as text.

**Comment by amir-zeldes** [comment]
OK, this is deployed to dev. Closed via efcb81b4.
