### ISSUE TITLE
Linking entries to Perseus 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#119]
Greek words can be linked to Perseus Greek morphology tool. Greek spellings are located: 

1. With loan words in `<etym><ref type="greek_lemma::grl_lemma">πνεῦμα</ref>` tag.

2. With Egyptian words the Greek equivalent is contained in  `<sense><ref type="Greek">κόραξ, κορώνη</ref>`. 

To preserve the stylistic unity with linking to Annis/CS, I suggest to use a Perseus icon/button. Note that in case (2) multiple synonyms can be listed separated by commas. This means they have to be displayed in a column with Perseus button next to each.

**Comment by amir-zeldes** [comment]
I'm looking at this now - I originally thought this sounds fine, but then I realized a few problems with putting the links in the top list:

1. If there are multiple variants which are legitimate, distinct Greek forms, then we'd need to link every form (so lots of Perseus links)
2. For forms other than the Greek lemma, we don't have a polytonic Greek representation, so linking becomes much more ambiguous. Perseus requires at least initial spiritus to look up, though it will attempt to guess accents
3. Even if we only want to use the lemma form, for which we have the polytonic representation, it only appears below in 'cf.', and it doesn't necessarily correspond to the Coptic lemma

To understand the last point, consider a verb like keleue:

  * The Coptic lemma is ⲕⲉⲗⲉⲩⲉ
  * The linkable polytonic Greek form is κελεύω
  * Since we're relying on Persues's morphological analysis, our link would would lead to: http://www.perseus.tufts.edu/hopper/resolveform?type=exact&lookup=keleu/w&lang=greek
  * This result seems natural if it's the actual `cf. κελεύω` which links to it, but it's more surprising if the form ⲕⲉⲗⲉⲩⲉ (or maybe even all of them, so also variants like ⲅⲓⲗⲉⲩⲉ) points to this first person Greek form

In sum, due to using the polytonic cf. form as the basis for the link, I think it would make the most sense to keep it at the bottom. I'm happy to give it a Perseus icon though, if you think that would look better.

**Comment by phoenix-mossimo** [comment]
> In sum, due to using the polytonic cf. form as the basis for the link, I think it would make the most sense to keep it at the bottom. I'm happy to give it a Perseus icon though, if you think that would look better.

Sure. I did not mean we have to put the Perseus button next to Annis, I was implying that using button is better then the word-link as it is now. Button at the end of the line starting with "cf." is perfectly fine with me ( I think Katrin suggested something similar in her screenshot). 


> If there are multiple variants which are legitimate, distinct Greek forms, then we'd need to link every form (so lots of Perseus links)

I think DDGLC data always have only one Greek lemma spelling per entry.  


> For forms other than the Greek lemma, we don't have a polytonic Greek representation, so linking becomes much more ambiguous. Perseus requires at least initial spiritus to look up, though it will attempt to guess accents

Ok, so linking Greek translations of Egyptian-Coptic words contained in `<sense><ref` type="Greek">κόραξ, κορώνη</ref>` is problematic?

**Comment by amir-zeldes** [comment]
Oh, I see, in that case it shouldn't be a problem. I just meant linking the entries at the top wouldn't be straight forward. For the sense-ref part, it could be possible, since they are polytonic. The main question is how consistent the use of commas etc. is: we need exactly and only polytonic Greek characters per link. If comma cases are the only exception, we can just split by `, ` (comma-space) and make multiple links. Is that the only format we'll get except single polytonic Greek word?

**Comment by amir-zeldes** [comment]
OK, I added a Perseus icon to the basic Greek lemma lookup in dev (without sense ref ATM). Does this look good?

**Comment by phoenix-mossimo** [comment]
Wasn't DDGLC willing to have a kind of prefix before the Greek form (something like "DDGLC Greek_lemma ID =1775"? Lets wait for Katrin's response.

**Comment by phoenix-mossimo** [comment]
Can you add "DDGLC Greek Lemma ID" info as follows, e.g. C9197:  

cf. DDGLC Greek Lemma ID 3296: θησαυρός  store, treasure. noun (LSJ 801a?; Preisigke 1:677?). 

As far as I understand this ID could in the future forward to the entry in DDGLC online database.

**Comment by amir-zeldes** [comment]
OK, I've added it in the dev instance. OK to close this?
