### ISSUE TITLE
Mobile view: the table of the search results does not autofit the window

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#12]
Search results (third column, translations) are squeezed out of the table. 

In contrast in "entry detail" the contents of all three columns are aligned correctly. 

@amir-zeldes @ctschroeder - check it out on your phones.

**Comment by amir-zeldes** [comment]
Actually, there is no difference between detail and search results. I can reproduce this, depending on the phone and entry, also in the details page, for example for ouhor:

https://corpling.uis.georgetown.edu/coptic-dictionary/entry.cgi?entry=5176&super=2025

It depends on how many characters appear before a line break can be made (long words cause the problem). I can also reproduce it on PC by making the windows narrow - it's not a mobile issue per se. The questions is what you would want to happen here. 

Options:
  * Do nothing. 
  * Add a scroll bar when the cell overflows (I just tried this, it looks very ugly I'm afraid)
  * Make the table broader by default. This will cause this to only happen if words are even longer, which is rare. However the whole table will always be bigger, meaning on phones the site will auto snap the zoom to fit that, and letters will de facto be smaller. On PC's it'll just look a bit broader.

I'm not super-keen on trying to develop optimizations for phones because of the variety of devices involved, but the above are easy options.

**Comment by phoenix-mossimo** [comment]
Are you sure the tables are the same? The 3rd column of the ´"entry detail" can squeeze up to 12 characters, the 3rd column of the "search results" gives up at 25 characters or so.  

Ex. Look for "hand", and in the list click on " ϯ	ϯ ⲛⲧⲟⲟⲧ⸗" "give hand" - the third column behaves differently with "search results" and "entry detail"

**Comment by amir-zeldes** [comment]
Yes, it's possible they behave a little differently, depending on the device, I just mean that the problem can occur on either page. So are you saying a little bit wider is the desired solution (num. 3 above)? I can do this, it'll just make everything a bit wider on PCs and the font a little smaller on mobiles due to auto-fit.

**Comment by phoenix-mossimo** [comment]
I mean: check the properties of tables on "search results" and " entry detail". If they are identical - do nothing. If not - share the properties of "entry detail" with "search results". I attached the screenshots from my Android phone - the first one is "search results", the second and the third - "entry detail"
![search_results](https://cloud.githubusercontent.com/assets/15609955/19779887/4068acf2-9c83-11e6-964d-6b9a65a48fb3.png)
![entry_detail_1](https://cloud.githubusercontent.com/assets/15609955/19779893/49892848-9c83-11e6-8faf-1ab3abfe56d6.png)
![entry_detail_2](https://cloud.githubusercontent.com/assets/15609955/19779901/4eb7dc9c-9c83-11e6-8f0c-d8d0d1af6d19.png)

**Comment by amir-zeldes** [comment]
This was a bit tricky since I can't reproduce this behavior on my phone, but the screenshots are very helpful. Now I was able to simulate a Samsung Galaxy to debug this, I think I see the problem.
