### ISSUE TITLE
Translations and bibliography not shown correctly

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#127]
With a number of entries translations and bibliography display strange behavior on test server: 

1) The are either not shown at all, e.g. C616-C619, C737.
2) Or they are shown, but the bibliographic hint ("?") is displayed in a wrong position (after Till, not after LCG),  e.g. C11278, C11279.

I wonder whether that may be again a case of pretty-print line-breaks.

**Comment by amir-zeldes** [comment]
Thanks for reporting, I'll look into it

**Comment by amir-zeldes** [comment]
Actually the reasons were different:

1. C616 etc. had `<def>` but not `<quote>` in the sense definition. I've adjusted the import script to handle this situation correctly, though I was a little surprised `<quote>` is not required
2. C11278 and C11279 had a comma separating the bibliographical sources instead of semicolon. I've fixed these two entries and they should work now online, but I think it should be corrected in the XML sources, since the semicolon is treated as a meaningful symbol for separating sources by the import script (and the number of links depends on it)

**Comment by phoenix-mossimo** [comment]
1. `<cit>` allows four elements: `<quote>` used for translations, `<def>` used for definitions (e.g. of functional words), `<note>` for explanations and `<bibl>` for bibliographic references. This is actually unchanged since the very first release. In the XML Scheme they are governed by `xs:choice`.  

2. Thanks, this is a bug. I cannot change it in the released V 1.2 XML, but I created a new issue and will pass it to the next version: #131

**Comment by phoenix-mossimo** [comment]
Bibliographic hint with C11278, C11279 still in the wrong position.

**Comment by amir-zeldes** [comment]
They look correct to me in dev:

![image](https://user-images.githubusercontent.com/2188635/89686030-82a47c80-d8cb-11ea-81b0-a4c3c3a043d1.png)

Are you still seeing the problem?

**Comment by phoenix-mossimo** [comment]
corrected. Closed with V 1.2
