### ISSUE TITLE
Lemma Form ID search dilemma 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#139]
Quick search is now looking for Form IDs and successfully finds **CF346**, which is non-lemma, but ignores **CF345**, which is a lemma-form. The latter behavior is logical, because Form IDs of the lemma is not displayed. Any creative ideas how this can be solved? I find this new feature (form ID search) quite useful, but it should function properly

**Comment by amir-zeldes** [comment]
OK, take a look now, I've added saving the lemma form xml:id behind the scenes, so you should be able to search for CF345 now and find the correct entry. Note that C11273 has no entry with the type 'lemma', so that particular entry has no corresponding lemma form search (although you could still find the inflected form CF1591)

**Comment by phoenix-mossimo** [comment]
Don't you think if would be user-friendly to display the CF of the lemma-form? Will the user not be buffled if something is found which is not dispalyed? 

Thanks for CF1591 - it is a bug, resulting from #46 and #34. Resolving bugs produces new bugs :-8.

**Comment by amir-zeldes** [comment]
Well... I can answer that on two levels: from the conceptual level, yes, I think it's confusing, but the confusing thing IMO is that the lemma form ID exists at all. There is an entry ID (the TLA ID), and there are IDs for each form, but the so-called lemma form is guaranteed to be identical to one of the listed forms AND is in a 1:1 relation with the entries. From a conceptual perspective, both lemma for ID and TLA ID are at the same level: they are unique identifiers for an entry. So I never really understood the rationale for a lemma form ID separate from the non-lemma form listing for that form and the TLA ID, but since this is the schema, I just accept that this is the case. 

But on a second level I think it doesn't really matter, since it's not likely that someone who is not intimately involved with the XML schema etc. will really search for words by form IDs. How would they even know what to search for? Users who do this are much less likely to have problems mentally mapping the interface to the XML files, and if the purpose is just to make sure that searching for that form ID gives you the right entry, then that is already supported. Just my 2c of course.

**Comment by dwerning** [comment]
Dear both, 
I feel like Amir, it is first seems confusing to have an extra ID for the lemma form at all. Indeed, I had suggested months ago to change the prefix from CF to LF (lemma form; or similar). But the IDs with "CF" were already pulished ... 
Anyhhow, having an extra ID for the lemma form has the benefit that this form can technically be different from all attested forms (e.g., normalized Greek spelling, not attested in the dictionary; or: Coptic form with brackets) and can be quoted by a seperate ID then. 
Anyhow, I am fine with _not_ displaying the lemma form ID on copticdictionary.org. The fact that the search for it brimgs one to the lemma, is what we need; plus: it prevents that users of copticdictionary.org (unwanted) cited the lemma by its lemma form ID, not (as wanted) by its TLA lemma no.

**Comment by phoenix-mossimo** [comment]
Ok, lets leave it like this. For C11273 I created #140.
