### ISSUE TITLE
Bad example sentence for the entry ϣⲓⲛⲉ (noun)

### ISSUE THREAD

**Issue by pinnerup** [KELLIA/dictionary#176]
Word you searched for in the dictionary (in Coptic):

ϣⲓⲛⲉ

TLA ID (shown at the top of the entry page after "TLA Lemma No."):

C5926

Bad example sentence (insert your example):

All of them.

Notes:

The examples use the word in the sense 'visit', but that sense has its own entry ('ϣⲓⲛⲉ ⲉ-'). This entry is for the sense 'news, report'.

**Comment by amir-zeldes** [comment]
Hm, this is a tricky one - the examples are probably all instances of ϭⲓⲛⲉ/ϭⲙⲡϣⲓⲛⲉ so it's this entry:

https://coptic-dictionary.org/entry.cgi?tla=C5931

But the noun in C5926 is the same morphological noun, it's just that "find someone's inquiry" means "visit". The actual sense of "inquiry" by itself seems to be very rare. Looking through the corpora we have, this is pretty much the only instance I can find:

https://corpling.uis.georgetown.edu/annis/?id=20ca5b32-d81c-424d-a7da-d03ac22cd2ca

And otherwise in Tim., the sense of ϣⲓⲛⲉ as a noun is more like "quarrel" or "dispute". I can't find a sense "news" anywhere in the Bible or elsewhere... @simondschweitzer @dwerning do you have some insight on whether this entry is justified as a separate sense, at least for Sahidic? Do you know other good OT or NT examples we could use? Or some other source?

**Comment by simondschweitzer** [comment]
> And otherwise in Tim., the sense of ϣⲓⲛⲉ as a noun is more like "quarrel" or "dispute". I can't find a sense "news" anywhere in the Bible or elsewhere... @simondschweitzer @dwerning do you have some insight on whether this entry is justified as a separate sense, at least for Sahidic? Do you know other good OT or NT examples we could use? Or some other source?

I do not know other examples than the ones Crum cited. Sorry.
