### ISSUE TITLE
Bad example sentence for the entry ⲕⲏ

### ISSUE THREAD

**Issue by ml4est** [KELLIA/dictionary#177]
Word you searched for in the dictionary (in Coptic): 
ⲕⲏ

TLA ID: 
C1059 

Bad example sentence:
ⲉⲁϥⲉⲡ ⲡⲛⲟϭⲛⲉϭ ⲙⲡⲉⲭⲣⲓⲥⲧⲟⲥ ϫⲉⲟⲩϩⲟⲩⲉ ⲙⲛⲧⲣⲙⲙⲁⲟ ⲡⲉ ⲉϩⲟⲩⲉⲛⲁϩⲱⲱⲣ ⲛⲕⲏ ⲙⲉ . ⲛⲉϥϭⲱϣⲧ ⲅⲁⲣ ⲡⲉ ⲉⲡⲧⲟⲩⲉⲓⲟ ⲛⲁϥ ⲙⲡⲉϥⲃⲉⲕⲉ .
accounting the reproach of Christ greater riches than the treasures of Egypt; for he looked to the reward.
58_Hebrews_11 (urn:cts:copticLit:nt.heb.sahidica:11)

Notes:
ⲛⲕⲏ in this example is misidentified as an instance of ⲕⲏ. Properly segmented it should be ⲛⲕⲏⲙⲉ (TLA ID: C1232).

**Comment by amir-zeldes** [comment]
This is interesting - the bad example is due to a segmentation error, which is just a data error from the original NT transcriptions.

But the real issue here is that we don't get any examples of statives of ⲕⲱ, which are plentiful, because in the corpora, the lemma of statives is the infinitive, so ⲕⲏ has the lemma ⲕⲱ. This normally works in the CDO examples, because most statives don't have entries: there is no entry for ⲟ (ⲉⲓⲣⲉ), ⲧⲟ (ϯ), ⲕⲏⲧ (ⲕⲱⲧ), etc., but the interface just redirects you to the infinitive, where you also see examples of the stative:

https://coptic-dictionary.org/entry.cgi?tla=C951

This works out in part because the example algorithm prefers to have diverse word forms with the same lemma in different examples.

@simondschweitzer @dwerning is there a rationale for having separate lexical entries for specific statives like ⲕⲏ, but not, say ⲕⲏⲧ? I could easily change the algorithm to look for examples for each stative to suit stative entries, but I'd like to understand the organizing principle of the XML entries a little better before tackling this.

**Comment by simondschweitzer** [comment]
> @simondschweitzer @dwerning is there a rationale for having separate lexical entries for specific statives like ⲕⲏ, but not, say ⲕⲏⲧ? I could easily change the algorithm to look for examples for each stative to suit stative entries, but I'd like to understand the organizing principle of the XML entries a little better before tackling this.

IMHO, a separate entry for a specific stativ only makes sense, if there is a specific sense which the user cannot anticipate from the verb. But this is not the case for ⲕⲏ. I do not understand why we have a separate ⲕⲏ. ⲕⲏ should be the same case as the examples ⲟ (ⲉⲓⲣⲉ), ⲧⲟ (ϯ), ⲕⲏⲧ (ⲕⲱⲧ) you cited. We do not need a separate entry for ⲕⲏ. Do you agree, @dwerning ?

**Comment by amir-zeldes** [comment]
OK I just did an update on the lexicon for another thing and decided to just treat **listed** statives as separate entries. So you'll now find examples in ⲕⲏ only come from the stative ⲕⲏ, etc.: 

https://coptic-dictionary.org/entry.cgi?tla=C1059

There are about 79 items like this, but some are multiword expressions, which were already based on norm retrieval, not lemma. Please let me now if you notice any issues.
