### ISSUE TITLE
ⲙⲉⲧⲁⲧϣⲧⲁϩⲟⲥ - seriously?!

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#186]
**Describe the bug**
Is this peculiar entry really a word?

**To Reproduce**
1. Go to ['...'](https://coptic-dictionary.org/entry.cgi?tla=C4747)
2. Check the Crum entry
3. Scroll down to "reftahe" and check the 4 lines just above that
4. See error: the ⲥ there is the feminine suffix and this whole piece of text got mistaken as a single word - it would appear

It's labelled Bohairic even, and the ϣ is unlikely to be part of it but my Bohairic is non-existent, though I know this says MNT-AT-something
Could you check?

https://archive.org/details/homliescoptesdel0000devi_r2q2/page/10/mode/2up LINE 6

**Comment by amir-zeldes** [comment]
I'm not sure what the bug is here - Crum also explicitly lists this form, and the form ϣ- for the potential auxiliary is compatible with both Bohairic and Sahidic:

https://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=541a&tla=C5673

But of course the form with ⲙⲉⲧ- is Bohairic. Is the problem that this is compositionally predictable and shouldn't have its own entry? Or is there a different problem? I presume the CDO lemma list just follows Crum here in treating this as a lexicalized entry of interest in its own right, but of course I agree its interior structure seems fairly straightforward.

**Comment by m-linssen** [comment]
ⲙⲉⲧⲁⲧϣⲧⲁϩⲟⲥ is the word according to the CDO, yet according to Crum the word is ⲙⲉⲧⲁⲧϣⲧⲁϩⲟ= and the =ⲥ is a pronoun suffic.
As such, this is just one example of what it could end up as, and it doesn't seem to be a word on its own.
Or am I completely misreading Crum and is ⲙⲉⲧⲁⲧϣⲧⲁϩⲟⲥ really a word, and does e.g. ⲙⲉⲧⲁⲧϣⲧⲁϩⲟϥ not exist?

"4. See error: the ⲥ there is the feminine suffix and this whole piece of text got mistaken as a single word - it would appear"

**Comment by amir-zeldes** [comment]
The question of "what is a word" is a highly complex one, and the bottom line is that there are no necessary and sufficient criteria for being a word. For a concise overview of the issues I recommend:

J. Mugdan (1994)
Morphological Units
The Encyclopedia of Language and Linguistics 5, 2543‐2553

Specifically regarding this entry and clitics, there are many lexicalized clitics which don't really mean anything because they are automatic. Some exist in alternation (ⲁϫⲓ vs ⲁϫⲓⲥ, where we could still claim the latter means something like "say it!"), and some are totally lexicalized, such as the -k in ⲙⲉϣⲁⲕ, originally "you never know" in older Egyptian, but in synchronic Coptic, effectively just a new adverb "maybe".

Crum seems to take the position that it is worth noting this form as a whole, and I certainly agree that the pronoun is not really referential or 'active' anymore. It's embedded into a sub-nominal structure: ⲧⲙⲉⲧⲁⲧϣⲧⲁϩⲟⲥ as if we said in English "the can't-understand-it-ness" or something like that, where the "it" is swallowed up inside the noun. The fact that this sequence is grammatical (and has a conventional meaning) is perhaps reason enough to include it in a dictionary.

Finally, for the CDO / lemma list, I'm guessing that the reason it was included is simply that it was listed in Crum, and not necessarily an in depth analysis of the inclusion criteria that went into Crum's dictionary in the first place.

Unless I'm missing a different issue, I'll go ahead and close this one!
