### ISSUE TITLE
https://coptic-dictionary.org/entry.cgi?tla=C10553 = LSJ *s111.78.stixhro/s

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#188]
This is the last one I'm reporting, I'd suggest you do a sanity check on them all. Whoever wrote these down wasn't very proficient in Greek, or didn't bother to verify them - or both

**Comment by amir-zeldes** [comment]
I'm not sure what the issue is here either - from the title of the issue, it sounds like you think the link should point to the masculine form in -os? If so, I would point out that in Byzantine liturgy the neuter form is used, even if LSJ lists this under the masculine form, see for example:

https://mci.archpitt.org/liturgy/Stichera.html

Or if the problem is something else, then please explain the issue more clearly.
