### ISSUE TITLE
Standard (non-regex) query does not find compounds anymore 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#19]
With V2.0 we exchanged all ```<form type="lemma">xxx```tags with cross-references: ```<xr type="cf"><ref target="#xxx">```. Thus: 
```
<entry type="compound">
<form>ϫⲓϫⲱⲕⲙ</form>
<form type="lemma">ϫⲓ</form>
```
is now: 
```
<entry type="compound">
<form>ϫⲓϫⲱⲕⲙ</form>
<xr type="cf"> <ref target="#ϫⲓ">nehmen, erhalten</ref></xr>
```
The consequence is that the compounds are not found anymore with the simple query like "ϫⲓ". I mentioned it in the "Release notes CLL V2.0", asking for modification of the query script: 

"Search query in “Coptic Dictionary Online” should additionally look up the value of the attribute "target" in ```<ref>``` tag  as well as the value of the attribute "type" in ```<gram>``` tag (the latter includes references to collocated adverbs and prepositions (ex. ```<gram type="collocPrep">ⲉϩⲣⲛ-</gram>```). 

Search results could thus be displayed in the folowing order: 

- lemmata found in ```<form>```, e.g.  ϫⲓ in ```<form>ϫⲓ</form>```
- lemmata found in ```<ref>```, e.g. ϫⲓ in ```<form>ϫⲓϫⲱⲕⲙ</form, <xr type="cf"> <ref target="#ϫⲓ">nehmen, erhalten</ref></xr>```
- lemmata found in ```<gram>```, ex. ϩⲛ in ```<form type="lemma">ϩⲛ ⲟⲩϫⲱⲗⲕ (ⲉⲃⲟⲗ)</form> <gram type="collocPrep">ϩⲛ</gram>```

This would also solve #2

**Comment by amir-zeldes** [comment]
Hm.. this conflicts with #16 since then, looking for "mnt" will find all mnt.* words (since they have a target ref to mnt). The problem is if we go this way, ALL target links will become search results. From your answer in #16 I understood that this wasn't desirable.

I think I raised this concern before, but the new lemma list generally seems to 'inflate' the number of hits. In the V1 schema, you were able to just not give out a form-tag, and then that would not have been an entry. This way, any target attribute presupposes an independent entry which will also be found in the search results. 

If you really want to do this we can look into it, but you should be aware that this may cause more hits than before in unexpected places. It's also not completely trivial in the current architecture, but should be possible with some work.

**Comment by phoenix-mossimo** [comment]
Yes, I warned about the "inflation", this is the unfortunate consequence of adapting CLL structure to TLA requirements, with the perspective of merging both. Because of this inflation,  #1 becomes more urgent. 

I don't think this conflicts #16, because ⲙⲛⲧ.* and ⲙⲛⲧ  are semantically two different types of search and ⲙⲛⲧ-/ⲙⲛⲧ= adheres to the latter. ⲙⲛⲧ.* will deliver more results, also due to the reason that not all compounds are cross-referenced. Still, I think we need to offer as much as possible via simple query, because most people wont even try regex.

**Comment by amir-zeldes** [comment]
I think we're not understanding each other, so let me clarify: since "mnt" is a target value in compounds, if we allow all searches to find the values in target, then any search for mnt (including if I search for mnt-, since the "-" will be stripped), will find all words in mnt. This seems to rob the user of the possibility to use regex to mean 'anything starting with mnt', and it isn't the behavior requested in #16 ('mnt' without regex finds only the entry for mnt itself).

I've been thinking about this and I'm not sure people expect 'ji' to find all compounds in 'ji' in the search results page already- that would lead to a very large, potentially distracting result list if you really do want to find ji. Just plain 'ji' already has four entries and 10 senses on the results page.

Maybe a better approach would be to put all of these compounds in the 'see also' part of the entry page for the appropriate 'ji'. Wouldn't that be more 'Crum-like'?

**Comment by ctschroeder** [comment]
Hi. I can't comment on the TLA integration, but for the dictionary itself, I do think "see also" would be preferable.  That way, the information is there if people want it, but the main list of entries is not overwhelming.  Especially for students or people whose primary research area is not Coptic, a "see also" list could work better, so they aren't overwhelmed by a long main entry list.

**Comment by amir-zeldes** [comment]
OK, I just discussed this with @purplatypus , we think the best way might be to just add a link at the bottom of the results saying 'include related entries'. If the user doesn't find what they want, they can click on that and get all entries including ones that point to a term matching the search.

**Comment by phoenix-mossimo** [comment]
yes, this is a good idea and the solution of #2 as well.
