### ISSUE TITLE
ϣⲧⲟⲣⲧⲣ isn't only intransitive (nor is ϣⲓⲡⲉ, and so on)

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#190]
Observe https://coptic-dictionary.org/entry.cgi?tla=C6120

1. | (En) | be disturbed, in haste, disturb
  | (Fr) | être bouleversé, troublé, troubler, déranger
  | (De) | bestürzt sein, aufgeregt sein, überhasten, stören
  | Bibliography: CD 597b-598b?; KoptHWb 332?; DELC 273a?; ChLCS 82b?

That's all the CDO says, yet it is transitive as well

Likewise for https://coptic-dictionary.org/entry.cgi?tla=C5986, and there undoubtedly will be others

I'm just going by my Thomas Commentary guys, it's not like I'm checking up on your work. And I didn 't even know any Coptic 2 years ago. Why don't you get Marcion and use that to cross-check your data? That data is absolutely pristine

**Comment by amir-zeldes** [comment]
I'm not sure I understand the issue. Where does it say that it is not transitive? I read the glosses "disturb", "troubler, déranger", and "stören" as all transitive. The same is true for C5986, which includes the glosses "be ashamed, shame, make ashamed", i.e. both intransitive and transitive. Or did I misunderstand the problem?

**Comment by m-linssen** [comment]
Hi Amir, I was under the impression that CDO entries don't say whether they're transitive or intransitive, that they contain both entries from Crum; these only have 1.Cf. https://coptic-dictionary.org/entry.cgi?tla=C951Then again, https://coptic-dictionary.org/entry.cgi?tla=C3828 only has "to choose" and only 1 entry as wellIt would seem that I expected a certain consistency where there appears to be none: sometimes transitive and intransitive have their own numbered entries, sometimes they share one and the same, and sometimes there is only 1 entry with 1 versionOdd that it never occurred to me before!
-------- Original message --------From: Amir Zeldes ***@***.***> Date: 20/12/2021  20:57  (GMT+01:00) To: KELLIA/dictionary ***@***.***> Cc: Martijn Linssen ***@***.***>, Author ***@***.***> Subject: Re: [KELLIA/dictionary] ϣⲧⲟⲣⲧⲣ isn't only intransitive (nor is ϣⲓⲡⲉ, and so on) (Issue #190) 

I'm not sure I understand the issue. Where does it say that it is not transitive? I read the glosses "disturb", "troubler, déranger", and "stören" as all transitive. The same is true for C5986, which includes the glosses "be ashamed, shame, make ashamed", i.e. both intransitive and transitive. Or did I misunderstand the problem?

**Comment by amir-zeldes** [comment]
I can't speak to the design principles of the lemma list in terms of when exactly a separate entry is created - but I imagine the same is true for English dictionaries where many verbs can productively undergo argument structure changes in context. Personally I would expect separate entries at the latest when there is a distinct and unpredictable meaning change, aside from the standard transitive/intransitive split. 

For example, ⲟⲩⲃⲁϣ in the infinitive means "become white", and despite the fact that for me the stative ⲟⲩⲟⲃϣ "be white" is a very useful word to remember that might deserve its own entry, this is really just a regular fact of Coptic grammar with quality predicates, so I understand why there isn't a separate entry for that. In any case, I would not treat this as a bug.

PS - it looks like when answering issue posts via e-mail your client creates somewhat garbled responses (see above in the GitHub interface) - since this is an archival platform, it might be a good idea to communicate using the GitHub site directly.

**Comment by m-linssen** [comment]
Hi Amir, regarding the PS: my client automatically includes the previous 
message - I will disable that feature when responding via email for 
github issues
