### ISSUE TITLE
ⲛ ⲧⲡⲉ is not an Adverb - nor is ⲟⲣⲇⲓⲛⲟⲛ, or (ϩⲓⲛⲉ)

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#192]
The first is an adjective (C4399), the second a noun (C9945) whereas its other form ⲟⲣⲇⲓⲛⲟⲛ (C9946) is an adverb - going by the translation, the LSJ pointers and ANNIS examples are rather confusing; it would seem that these two got mixed up.
In addition to that, (ϩⲓⲛⲉ) is a verb - C6704

https://coptic-dictionary.org/entry.cgi?tla=C10827 is really extraordinary with the POS saying Adv., the translation saying substantive, and LSJ saying adjective

ⲟⲩⲛϩⲱⲃ ⲙⲛ- would seem to be an auxiliary verb but I'll gladly let you be the judge of that (and of any of these, for that matter)

I'd change the definition of https://coptic-dictionary.org/entry.cgi?tla=C7272 to say violentLY, forcibLY in order to comply with its classification

**Comment by amir-zeldes** [comment]
There are several issues here:

  * C4399 - ⲛⲧⲡⲉ - if we accept that this phrase (which is morphosyntactically a prepositional phrase) merits a lexicon entry, then seeing it as adverbial is not wrong (prepositional phrases taken as a whole can function adverbially; "adjective" is a problematic term in Coptic, except for the small class of words like ϣⲏⲙ, ⲁⲥ etc.)
  * ⲟⲣⲇⲓⲛⲟⲛ should indeed have a noun entry as well, so I think C9945 should be corrected as you say
  * I'm not sure what's happening in C6704, or why it has an asterisk, so I will defer to @dwerning on this one. I think the issue is that the base form is unattested in Sahidic?
  * C10827 - I only know this word as an adverb in Coptic, but usually with omega, see https://corpling.uis.georgetown.edu/annis/?id=fb956127-2559-4e64-ac03-23b45de86aec ; It's possibly an adjective in Greek but maybe used more often as an adverb in Coptic? What LSJ says is less relevant, since the POS tags in CDO / Scriptorium data should only be based on Coptic grammar (just as we ignore etymology in POS assignments in English dictionaries)
  * ⲟⲩⲛϩⲱⲃ - I'm not sure which CDO entry we're talking about, can you list the TLA ID?
  * C7272 - The French and German definitions are correct (adverbial meaning), but the English one is inaccurate

**Comment by amir-zeldes** [comment]
@dwerning @simondschweitzer @KaJohn-DDGLC Since this issue has been stale for a long time, I pushed an update to the dev branch here: ffda2d1

Can you verify that the changes look good and merge them into your working sources?
