### ISSUE TITLE
Wrong page listed for Crum link

### ISSUE THREAD

**Issue by amir-zeldes** [KELLIA/dictionary#198]
Reported by a user: 

ϩⲁⲏ, meaning “end” or “last” (e.g., Mt 24:14; Mk 3:26; etc.) should be keyed to Crum Dict. 635a - 636a (< s.v. ϩⲁⲉ): NOT Crum 636-b, (s.v. ϩⲁⲏ), “animal(?)”

Once this is fixed in the XML I can propagate to the interface.

**Comment by simondschweitzer** [comment]
I don't really get this issue, sorry. We have the two lemmas ϩⲁⲉ (C6338 and C6339). This is CD 635a-636a. The animal ϩⲁⲏ is CD 636b. Should I add an additional spelling ϩⲁⲏ for the lemmas ϩⲁⲉ (C6338 and C6339) because Mt 24:14; Mk 3:26 (and CD 635a) have ϩⲁⲏ for ϩⲁⲉ? Or is the existence of the lemma ϩⲁⲏ (C6348) the problem?

**Comment by simondschweitzer** [comment]
IMHO, the bibliographical reference of C6340 is correct because the information on the adjective starts in column b. The one entry at Crum corresponds to several entries at our site. Therefore, in my opinion, the bibliographic entries in our database should not cover the whole spectrum of Crum. Do you think so too, Daniel? @dwerning

**Comment by amir-zeldes** [comment]
Actually I also agree with you, this was a misunderstanding and can be closed IMO. Sorry about that!
