### ISSUE TITLE
Missing word ⲛⲧⲃⲁⲣⲃⲏⲗⲱ Barbelo entry is missing RE (Pistis Sophia)

### ISSUE THREAD

**Issue by Nostradamus888** [KELLIA/dictionary#234]
**Describe the bug**
Missing word ⲛⲧⲃⲁⲣⲃⲏⲗⲱ Barbelo entry is missing RE (Pistis Sophia)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amir-zeldes** [comment]
Hi and thanks for reporting! I'm afraid this word is out of scope for what the dictionary sets out to do: first, the form "ⲛⲧⲃⲁⲣⲃⲏⲗⲱ" is a bound group, so it would only be possible to include "ⲃⲁⲣⲃⲏⲗⲱ" by itself; but even then, this is a proper name, rather than a Coptic word, and we don't generally make lexicon entries for names. That said, if you want to find occurrences or get frequency information about names, you can use our ANNIS search interface to get attestations and statistical information - see the tutorial here:

https://copticscriptorium.org/ANNIS_tutorial

The part of speech tag for names is `NPROP`.

**Comment by Nostradamus888** [comment]
Thanks for the kind reply Amir.
Via gematria I believe it is possible to investigate spiritual potencies in words.

Cheers
God be with you.

Richard
