### ISSUE TITLE
Dialect K is Missing from the Filter List

### ISSUE THREAD

**Issue by pishoyg** [KELLIA/dictionary#254]
**Describe the bug**
The list of dialects in the drop-down menu on https://coptic-dictionary.org/ is missing one dialect - `K`.

**To Reproduce**
1. Go to https://coptic-dictionary.org/
2. Click on the _Dialect_ dropdown menu.
3. `K` is not there.

P.S. Which dialect is that? Is it one of those Kasser — Satzinger dialects identified by a single manuscript? Or is it a popular dialect?

**Comment by pishoyg** [comment]
Here is an example of a word belonging to this dialect: https://coptic-dictionary.org/entry.cgi?tla=C2537.

**Comment by amir-zeldes** [comment]
Thanks for reporting. From looking at a few entries I think this might be ["Old Coptic"](https://en.wikipedia.org/wiki/Old_Coptic) - but let's get some clarity before revising the interface @dwerning @simondschweitzer - could you let us know what the dialect siglum K stands for?

**Comment by pishoyg** [comment]
If it's Old Coptic, is it the same as `Ak`? Or is another variety of Old Coptic?

**Comment by pishoyg** [comment]
Is [this line](https://github.com/KELLIA/dictionary/blob/d315fccbe58da755b7360e7a01bf460a9f94fa41/utils/dictionary_reader.py#L41) the source of all the `K` words?

[`Comprehensive_Coptic_Lexicon-v1.2-2020`](https://github.com/KELLIA/dictionary/blob/master/xml/Comprehensive_Coptic_Lexicon-v1.2-2020.xml) doesn't have any entries with the `geo` field set to `K`.

**Comment by amir-zeldes** [comment]
Oh, yes, you're right. It looks like the student who wrote that code wanted all sigla to be single letters so they just abbreviated it, and I guess "A" was already taken up by Akhmimic. 

OK, so that settles it, K is Ak, short for Altkoptisch, so it's definitely Old Coptic. I also see searches actually work fine in the background, so picking "Ak" in the interface finds the "K" entries. I can fix the visualization so it displays as "Ak" without too much trouble I think.

**Comment by amir-zeldes** [comment]
Now it displays correctly (internally it's still "K", since I'm not sure if the single character length is relied on anywhere, but that shouldn't matter):

![image](https://github.com/user-attachments/assets/d7d82d38-027b-4f5b-9b13-cc9606c40d9c)
