### ISSUE TITLE
Query is not displayed with search results 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#3]
Steps to reproduce: 

Search for "ϫⲓ" either in "Quick search" or in regular search: I get results, but not my query. Just leave the query in the search field.

**Comment by amir-zeldes** [comment]
There are several ways to implement this:
  * Have a textual representation of the query ("you searched for XYZ")
  * Implanting the values into the quick search box.

The second option is problematic, since a complex search may not be representable in the quick search box. For example, if you search by dialect or tag, that information cannot be displayed in the that field on the results pages. 

I would therefore be more for option 1, with the addition that if the user did use quick search, whatever they input can remain in the quick search box in the results page. But this would not be a substitute for option 1, telling you exactly what you searched for. @phoenix-mossimo: does that make sense?

**Comment by phoenix-mossimo** [comment]
If I understand it correctly:

Option 1 (textual representation) for both "quick search" and "regular (complex) search" results
Option 2 for "quick search" only.

Yes, this is OK.
