### ISSUE TITLE
stable URL for entries based on TLA lemma no.

### ISSUE THREAD

**Issue by dwerning** [KELLIA/dictionary#51]
(after pull of masterBBAW branch)
- design URL in a way that it is stable and citable based on TLA lemma no., e.g., https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?**entry=CF8058**
- add this URL pattern to citation string in entry.cgi (marked: "##TODO##")

**Comment by amir-zeldes** [comment]
OK, this is implemented in 3beb109d08245fcc47057c0c5a70d1a07aed854a for example:

https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?tla=C3816

**Comment by dwerning** [comment]
nearly nice. However, 
- the C3816 in the URL does not lead to C3816, but to CF9557 ?!? (C are lemma nos. CF are form nos.)
- of the no in the URL is not in the database, an Python error is raised, e.g. https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?tla=C38161111 There should be a nicer info ;)

**Comment by amir-zeldes** [comment]
Agreed, I will make a proper 'not found' solution. I don't understand the first problem though, this link does lead to C3816, as shown in the title of the page:

https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?tla=C3816

The ID CF9557 belongs to the first (and only) form element under that lemma number, but there are many entries that have multiple CFs under the main C- entry:

https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?tla=C615

**Comment by dwerning** [comment]
I see... 
(a bit confusing in the case of https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?tla=C3816 though)

**Comment by dwerning** [comment]
I moved the citation info on entry.cgi to a box at the buttom.
if the respective pull request works fine, we can close this ticket, right?

**Comment by phoenix-mossimo** [comment]
Reopened to clarify one issue: the current URL, shown in the browser after the search has been conducted, does not correspond to the citation URL. Examples:  

1. Look for "ⲕⲁⲧⲁ" (kata)
2. Result: 
URL: https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?entry=9361&super=4679
Entry TLA lemma no. C9360
Citation: http://www.coptic-dictionary.org/entry.cgi?tla=C9360 

1. Look for "ⲱⲙⲥ" (oms)
2. Result: 
URL: https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?entry=5478&super=2127
Entry TLA lemma no. C5476
Citation: http://www.coptic-dictionary.org/entry.cgi?tla=C5476 

Is that the intention?

**Comment by amir-zeldes** [comment]
Mm... it's not necessarily intentional, it just hasn't been changed yet. We do still need the super IDs since they link up related entries, but we can decide to display the TLA ID instead by default. 

Currently the system tacitly assumes that TLA IDs exist, but if we want them as a primary key then we need to absolutely ensure that they are always assigned and unique. If it's guaranteed this won't cause trouble, then we can change. To be clear, that would mean we can't ever include an entry before it gets assigned a TLA ID, so if in the future project X contributes a huge inventory of, say, Bohairic entries, we can't make them searchable until TLA has finished indexing them, which could cause delays in releasing new materials. The same goes for including new entries derived from annotated corpus material, etc. etc.

**Comment by dwerning** [comment]
We would like to have the TLA IDs mentioned as it is.

I suggest to make a table out of the upper part, wich new table heading
**Form | Dial. | TLA form ID | POS | ANNIS**
ⲕⲁ | S | CF23565 | Präp. | [*] 19
ⲕⲁⲧⲁ | L | CF23566 | Präp. | [*] 19  

BTW: is the TLA POS not always the same in the column. If so it should probably be displayed parallel to "Scriptorium Tag" which is likewhise a POS?
**Form | Dial. | TLA form ID | POS | ANNIS**
ⲕⲁ | S | CF23565 |  [*] 19
ⲕⲁⲧⲁ | L | CF23566 | [*] 19  
TLA POS: Präp.
Scriptorium POS: PREP

**Comment by phoenix-mossimo** [comment]
On our side we can guarantee that all released forms and entries will have stable unique IDs. This is a key prerequisite for linking the Coptic lexicon with the existing the Egyptian and Demotic data-sets, which is the goal of TLA. I was trying to envision under which condition (except error) the forms would be without IDs and could think of one (unlikely) scenario - to differentiate "active" and "non-active" items, which due to whatever reason are not supposed to be displayed / published / cited. I can't say why this should happen, but for now the rule the rule of thumb is that all published forms and entries must have stable IDs.

Considering the second part of your remark - TLA-DDGLC certainly does not have a monopoly on lexicographical work in Coptic. What we can offer is a stable data-model and (some) experience, also in matching different data structures . This does not exclude the possibility of the alternative input methods - for example, how about an online form "Submit new entry" direct in CDO, where the users could suggest their lemmata?

**Comment by amir-zeldes** [comment]
That sounds like a good idea - would you be able to create a process for assigning future IDs for items that are not yet in the TLA? Would we need an ID region that is 'free' (so not yet used up for Coptic or earlier Egyptian lemmas, assuming some mapping already exists)? Or would new IDs be assigned as we go by upticking the maximal ID?

**Comment by amir-zeldes** [comment]
OK, this is now implemented in 4891553 and deployed

Let me know what you think about the above!

**Comment by dwerning** [comment]
Mini-Bug: Coptic lemma not shown in Citation box.

**Comment by phoenix-mossimo** [comment]
I created two new issues: #62 (feature request assigned for v2) and #61

This one is closed.
