### ISSUE TITLE
Spell out "TLA form no. CF xxxx" in the entry details

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#55]
I find the ID information with entries, containing one form only, a bit misleading. For example with "ⲣⲱⲙⲉ" (pome): 

On top: Entry TLA lemma no. C3092
Below: ⲣⲱⲙⲉ	TLA: CF8058	Subst. f.	

The user is supposed to guess that the second ID is not a lemma ID, but something else. He also should understand that this is not a citation ID, although it is placed right next to the spelled form. 

I suggest spelling out "TLA form ID" with all form IDs.

**Comment by amir-zeldes** [comment]
I agree this is confusing, but TBH I think spelling out even more is actually more distracting (all forms have form ID, so just listing "TLA form ID" in every row could look clunky).

Also in view of @ctschroeder 's comments on the citation box, I think I would prefer hiding all IDs initially (lemma and form, since most users don't care this is lemma C3092), and just add buttons or pop-up hints to show them. For example, instead of having a huge title "Entry TLA lemma no. C3812", we could save that space and have a little button that says "cite", which would pop up the lemma ID and the contents of the citation box for this item (like SemanticScholar's 'cite' button). Similarly, instead of having "TLA form ID XYZ" displayed for every row, we could have a little font-awesome tag icon, which shows "TLA ID for this form: XYZ" on hover, again relieving some of the clutter that most users don't care about. What do you think?

**Comment by dwerning** [comment]
We would like to have the TLA IDs mentioned as it is.

I suggest to make a table out of the upper part, wich new table heading
Form | Dial. | TLA form ID | POS | ANNIS
ⲕⲁ | S | CF23565 | Präp. | [] 19
ⲕⲁⲧⲁ | L | CF23566 | Präp. | [] 19  

BTW: is the TLA POS not always the same in the column. If so it should probably be displayed parallel to "Scriptorium Tag" which is likewhise a POS?
Form | Dial. | TLA form ID | POS | ANNIS
ⲕⲁ | S | CF23565 | [] 19
ⲕⲁⲧⲁ | L | CF23566 | [] 19
TLA POS: Präp.
Scriptorium POS: PREP

**Comment by amir-zeldes** [comment]
The TLA POS can vary by row, since inflected forms (presuffixal, prenominal, etc.) can have their own tags, for example ⲁⲣⲓ:

https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?entry=195&super=116

The Scriptorium tag is a generalization over inflected tags, so in this case the entry receives the tag `V`, which is the tag for the lemma ⲉⲓⲣⲉ, even though the Scriptorium tag of ⲁⲣⲓ itself if `VIMP` (but this is not a lemma in the Scriptorium ontology). So each lemma entry receives a single Scriptorium tag to make searching a bit easier, but the TLA form entries within a lemma can (and do) have different tags.

**Comment by ctschroeder** [comment]
As a user: 
- the entry id is less important to me than almost anything else on the page
- I would prefer the citation not to be a popup.  We want to encourage people to cite (even though we recognize most won't or won't need to) and normalize the practice by making it visible.

**Comment by phoenix-mossimo** [comment]
All forms in one entry MUST have the same POS (<pos>Subst.</pos>) in XML code, but they often vary in "Subcategory" information (<subc>Ortsname</subc). Both types of information are displayed in one line on CDO. Same <pos> pro entry is a requirement of the TLA data model and is consistent (if not - let me know - it is a bug!).

Concerning the TLA Lemma no. display - I think we need it, but the layout could be adopted. Before discussing this, two related problems: 

1) the standard (citation) form, to which the citation below is provided is not displayed (i.e. <form type="lemma">: we know that it is one the of the forms listed below, but the user does not)
2) what if the user wants to site the spelling of individual form - do they cite the whole entry, without referring to a specific form?

**Comment by amir-zeldes** [comment]
I think 1. will be solved if we ensure the type="lemma" form is always first, i.e. it is the headword form. 

For 2. I think users could hypothetically cite the form IDs. TBH this is not something you could do in Crum (you could cite an entry, and then mention a form within it), so even though I think in practice users would cite entries, it's nice that the possibility is there.

**Comment by dwerning** [comment]
table header added https://github.com/KELLIA/dictionary/commit/28304687341b7d6519bff56d46b8fb8534cbc711
