### ISSUE TITLE
Display the entry citation form (form type="lemma")

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#57]
There are the following reasons for that:

- citation of "TLA lemma  no. xxx" is offered, but it is not clear to what spelling it refers;

- the first listed form is not necessarily the standard (lemma) form;

- the "Search results" display the first form of the XML entry, but not the lemma form (which is misleading): e.g. https://corpling.uis.georgetown.edu/coptic-dictionary-test/results.cgi?quick_search=ⲡⲣⲟⲃⲟⲗⲏ (left column)

According to DDGLC this is a critical bug (see excerpt from the email below)

**Comment by phoenix-mossimo** [comment]
> Darstellung von DDGLC-Entries ohne Lemma-String (This is a No Go!):

Dies ist ein grundsätzliches Problem. Der Inhalt von `<orth>` innerhalb
aller `<entry><formtype="lemma">`  scheint für die Anzeige vollständig
ignoriert zu werden.

Bsp. `<entryxml:id="C8892">
    <form xml:id="CF21628" type="lemma">
     <orth>ⲉⲓⲧⲉ</orth>
    </form>` 

Die Anzeige des entries
https://corpling.uis.georgetown.edu/coptic-dictionary-test/entry.cgi?entry=8893&super=4211
zeigt nicht die Standard-Schreibung ⲉⲓⲧⲉ (= der Lemma-String ist nicht
sichtbar). Da unsere Formen alphabetisch geordnet sind, erscheinen häufig
gekürzte, Nicht-Standard-Schreibungen als erste Form, um welches koptische
Lemma es sich handelt ist nicht ersichtlich (abgesehen von der ID).

Gilt das auch für den TLA-Teil des Lexikons?

Man muss sogar einschätzen, dass die erste nicht as Lemma deklarierte Form
als "Stichwort" her hält. Vgl. eine Ergebnisanzeige
https://corpling.uis.georgetown.edu/coptic-dictionary-test/results.cgi?quick_search=%E2%B2%A1%E2%B2%A3%E2%B2%9F%E2%B2%83%E2%B2%9F%E2%B2%97%E2%B2%8F.
Die anklickbaren strings (= Entries), entsprechen der ersten Form, sollten
aber den Lemmastring angeben. Dies wären ⲡⲣⲟⲃⲁⲗⲉ und ⲡⲣⲟⲃⲟⲗⲏ. Dieses
Entry-treatment ist inhaltlich schlichtweg falsch und kann so nicht
bleiben. Das betrifft (bis auf zufällige Ausnahmen, wenn die erste Form
dem Lemmastring entspricht) den gesamten DDGLC-Teil! Das geht so nicht.

Wir würden für die Darstellung folgende drei Änderungen anfragen: Der
Lemmastrimg muss bei Entry-Anzeige den Lemmastring klar und deutlich als
erstes (sichtbar abgesetzt) zeigen.

**Comment by amir-zeldes** [comment]
The desired first form is always clearly marked as the lemma in the XML, right? If so this should be easy enough to do.

**Comment by phoenix-mossimo** [comment]
The citation form is always marked as `form type="lemma"` and it is the first one in the list of forms. After  the non-lemma forms follow - organized alphabetically in Greek-Coptic case or according to Crum in Egyptian-Coptic case.

**Comment by amir-zeldes** [comment]
I had a quick look - the reason it's not in order is that the dictionary reader ignores the lemma entry, since it expects the same form to appear later. We could flip this around (ignore the later duplicate instead), but I noticed the lemma and the duplicate have distinct form IDs:

```
        <form xml:id="CF27005" type="lemma">
          <orth>ⲡⲛⲉⲩⲙⲁⲧⲓⲕⲱⲥ</orth>
          <usg type="geo">?</usg>
        </form>
        <form xml:id="CF27006">
          <orth>ⲡⲛⲉⲩⲙⲁⲧⲓⲕⲱⲥ</orth>
          <usg type="geo">?</usg>
        </form>
```

I think we definitely don't want to see both in the entry page, since they are 100% identical except for the ID - but which ID should we choose?

**Comment by KaJohn-DDGLC** [comment]
From a (meta) lexicographical point of view both ‘forms’ should be present, just in different places because of their different function. The ‘lemma string’ as the headword of the entry (macrostructure), the ‘form’ in the list of forms (microstructure). The best position for displaying the ‘lemma string’ would in a line with ‘Entry TLA lemma no. XXX’.

**Comment by amir-zeldes** [comment]
Thanks for commenting, there's no problem listing the lemma form at the top of the entry, but that's purely an interface question. I think the problematic part is the data model issue: we currently have three numbers representing the lemma form.

  * The entry ID, which has a unique lemma form under it
  * The lemma form element, which has a unique form ID
  * Another form which is identical to the lemma form and has yet another ID

I think we should eliminate the third one. The reason is that from an informational perspective the third is completely redundant with the second. The first ID could be argued to represent the entire entry (as in Crum) and is a citable identifier for all forms of that entry. The second identifies the particular form that is considered the citation form. But if we want form IDs in the entry detail table, then I think it would be distracting and space-wasting to have two identical forms listed in every single entry, and more so, it would confuse users who want to cite form IDs as to which one should be cited.

**Comment by phoenix-mossimo** [comment]
> I think we definitely don't want to see both in the entry page, since they are 100% identical except for the ID - but which ID should we choose?

Why not? 

I would use: 

- entry ID + lemma form (without ID)
- form ID 

For example: 

**Entry TLA lemma no. C8062: ⲁⲅⲅⲉⲗⲟⲥ** (without form ID)

**Forms**

 Form | Dialect | TLA form ID  | POS
-- | -- | -- | --
ⲁⲅⲅⲉⲗⲟ | S | CF18247 | Subst. |   |  
ⲁⲅⲅⲉⲗⲟⲥ | A | CF18248 | Subst. |   |  
ⲁⲅⲅⲉⲗⲟⲥ | M | CF18249 | Subst. |   |  
ⲁⲅⲅⲉⲗⲟⲥ | S | CF18250 | Subst. |   |  
ⲁⲅⲅⲉⲗⲟⲥ | B | CF18251 | Subst. |   |  
ⲁⲅⲅⲉⲗⲟⲥ | F | CF18252 | Subst. |   |  
ⲁⲅⲅⲉⲗⲟⲥ | L | CF18253 | Subst. |   |  
ⲁⲅⲅⲉⲗⲟⲥ | V | CF18254 | Subst. |   |  
ⲁⲅⲅⲉⲗⲱⲥ | S | CF18255 | Subst. |   |  
ⲁⲅⲉⲗⲗⲟⲥ | S | CF18256 | Subst. |   |  
ⲁⲅⲉⲗⲟⲥ | S | CF18257 | Subst. |   |  
ⲁⲅⲉⲗⲱⲥ | S | CF18258 | Subst. |   |  
ⲁⲕⲉⲗⲟⲥ | S | CF18259 | Subst. |   |  
ⲁⲛⲅⲉⲗⲟⲥ | S | CF18260 | Subst. |   |  
ⲉⲅⲅⲉⲗⲱⲥ | S | CF18261 | Subst. |   |

**Comment by KaJohn-DDGLC** [comment]
Yes, that's the desired output.

**Comment by amir-zeldes** [comment]
Yes, this should be fine - it means you're choosing to drop the ID of 2. in my comment, instead of 3. - either way is fine, as long as we don't use the form ID of the 'lemma' element. But in that case you could also just use the ID of the desired form as the actual ID attribute of the lemma instance, and also remove the redundancy in the XML files. The visualized output would remain exactly the way you want it. 

Let me know if you plan to modify the XML files to remove the redundancy and I can adjust the import script to match whichever scenario you prefer.

**Comment by phoenix-mossimo** [comment]
Hm, I am not entirely convinced (in Joshka Fisher's words :-) ) that CF in the lemma ID is redundant, even though, yes, it is a copy of the existing form. For now I would prefer not to touch the published XML with DOI. If we decide to remove CFs of lemma forms, that could be done with the next version (v1.1 or v2).

Cannot you just ignore the CF when displaying the lemma form? That should be easy.

**Comment by KaJohn-DDGLC** [comment]
> For now I would prefer not to touch the published XML with DOI. If we decide to remove CFs of lemma forms, that could be done with the next version (v1.1 or v2).

Fully supported :)

**Comment by amir-zeldes** [comment]
Done!
