### ISSUE TITLE
Insert lemma form into the citation 

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#61]
Please insert the lemma form in the citation box (@dwerning where exactly?): 

(TLA lemma no. C9360: **ⲕⲁⲧⲁ**), in: Coptic Dictionary Online, ed. by the Koptische/Coptic Electronic Language and Literature International Alliance (KELLIA), http://www.coptic-dictionary.org/entry.cgi?tla=C9360 (accessed yyyy-mm-dd).

Relevant question: Entry and citation use "TLA lemma **no.**". The table operates with "TLA form **ID**". Should it be not consistent to have either "no." or "ID"?

**Comment by dwerning** [comment]
IMO it should be:
TLA lemma no. C956 (ⲣⲁ), in: _Coptic Dictionary Online_, ...
TLA lemma no. C3029 (ⲣⲁ), in: _Coptic Dictionary Online_, ...
- with "no." instead of "ID"
- with the Coptic string in brakets (not the TLA no), since it is the no. which is unique not the string (as in the examples above)
- both identical string in heading and citation string:
"Entry TLA lemma no. Cxxx (ⲁⲁⲁⲁ)" in the heading
"TLA lemma no. Cxxx (ⲁⲁⲁⲁ)" in the citation string

**Comment by amir-zeldes** [comment]
OK, this is done. I think since new ideas keep piling up but we are not releasing as a result, we need to have a milestone system set up where some of these requests should be delayed until after the initial release. I'll also set up a dev branch so that the released version can be in master and we can easily revert test instances to it. Dev will not be guaranteed to be stable, but master should be.
