### ISSUE TITLE
CDO entry page design in mobile

### ISSUE THREAD

**Issue by ctschroeder** [KELLIA/dictionary#67]
Hello! I appreciate everyone's work thus far and am excited for the new developments. 

I used the development site on mobile, and I see that the grid approach for the top of the entry is not aligned in mobile. 
![cdo-test-mobile](https://user-images.githubusercontent.com/4079217/59245748-d4ba1700-8bce-11e9-8765-00f8a26abfce.png)

Compare to the layout on the primary URL:

![cdo-mobile](https://user-images.githubusercontent.com/4079217/59246915-9c1c3c80-8bd2-11e9-96a7-fa601cb3f3f3.png)

Additionally the "Senses:" header is a bit confusing; "Senses" is not a category/header native English speakers expect to see in a dictionary. The current trend in user-centered web design is also more minimalistic.

To provide a strong **user-centered design** interface I suggest the following design changes, which should not take much time:

1. We return to a design without the grid and headings.  Instead something like the old layout without headingss would work. 
     lemma dialect pos 3-attestations-icons
     TLA form ID: 
     Scriptorium tag:
     [list definitions in numbered list without "Senses:" as in the previous version]

     (This layout also means that if dialect is missing from the entry, we don't have a gap in the grid, which I believe was a concern.)

2. Change the header from "Entry TLA lemma no. ### (LEMMA)" to "LEMMA (TLA lemma no. ###) or two lines with LEMMA on the first line and TLA lemma no. ### on the second line possibly in smaller type.  In terms of **user-centered design**, the user wants to see the LEMMA (superentry, yes?) immediately at the top.  The TLA number is very important to ensure that the TLA's labor and intellectual work is credited, and I would never recommend anything that obscures the TLA number. The number itself is not memorized by most users, while the lemma is memorized and recognizable. The user wants to see the lemma in the primary position on the screen.

I believe these changes will result in an effective presentation of the data for our users while also providing the information and references all partners desire.

Thank you!!!

**Comment by dwerning** [comment]
Dear all,
Dear @ctschroeder 
Thank you for your review of the current state.

>  grid approach for the top of the entry is not aligned in mobile

Indeed it is aligned!? We could operate with colors in the headings to make that more clear. 

> lemma dialect pos 3-attestations-icons
TLA form ID:
Scriptorium tag:

To understand the grid and why the form ID cannot be in a seperate line, query, e.g., for "ⲁⲅⲅⲉⲗⲟⲥ".

![Bildschirmfoto vom 2019-06-11 um 09 59 19](https://user-images.githubusercontent.com/33833393/59254281-2f378f80-8c30-11e9-8f0a-00e87a0c844a.png)

> "Senses" is not a category/header native English speakers expect to see in a dictionary.

I am always confused about "senses" vs. "meanings". If the list, e.g., in the case of "ⲁⲅⲅⲉⲗⲟⲥ" returns four different translations "angel", it is four "senses", isn't it? Or, would "meanings" be more appropriate here?

> Change the header from "Entry TLA lemma no. ### (LEMMA)" to "LEMMA (TLA lemma no. ###) or ...

We discussed this topic in #61. The thing is that there are homonymous lemmata, e.g., 
TLA lemma no. C956 (ⲣⲁ), in: Coptic Dictionary Online, ...
TLA lemma no. C3029 (ⲣⲁ), in: Coptic Dictionary Online, ...
So the _unique_ part of the entry title, i.e. the ID should rather be more prominent, i.e. first/outside brackets, in the heading=citation string, we think.

Cf. also the discussion in #65. 

> the user wants to see the LEMMA (superentry, yes?) immediately at the top. 

Concerning this, and in order to prevent confusion, I would like to remind the idea (from #65) to add lemma information in the box (not just in the heading), e.g.,
> Lemma | TLA lemma ID | ANNIS
ⲕⲁⲧⲁ | C9360 | [ANNIS "lemma" links]

> Form | Dial. | TLA form ID | POS | ANNIS
ⲕⲁⲧⲁ | L | CF23566 | Präp. |  [ANNIS "norm" links]  
ⲕⲁⲧⲁ | S | CF23567 | Präp. |  [ANNIS "norm" links]  

(_Then_ we could also shorten "TLA lemma ID"/"TLA form ID" to "TLA ID".)

**Comment by phoenix-mossimo** [comment]
How about changing the the text alignment in the tables from "centered" to "top"?  The rest looks fine to me.

**Comment by amir-zeldes** [comment]
I'll resolve the dialect issue, hopefully later today. The separate lemma link is a potential pitfall since ANNIS lemmas are not the same as CDO lemmas, so probably the solution using "OR" (AQL `|`) is better, plus having the lemma three times or more on each page seems confusing to me.

Let me take a closer look at this in mobile dev mode and I'll get back with a draft suggestion soon. I also think we should converge on a release candidate, ideally this week.

**Comment by amir-zeldes** [comment]
OK, so this is what I have now in mobile mode:

![image](https://user-images.githubusercontent.com/2188635/59295983-e80ec600-8c52-11e9-92d7-5111038c92cc.png)

A few notes:

  * I understand Carrie's point about the lemma being what the user wants, but I also understand Daniel's point about the multiple ambiguous entries, so I decided to put the Coptic lemma not in brackets, but in a new line, so both are prominent and easy to identify. I hope this is a good compromise?
  * I realigned the logos without removing the table, and adjusted the headers so things generally fit if it's not a really tiny phone. If so, it will just wrap, so it's not catastrophic.
  * I removed the heading 'senses', which I suppose could be distracting and is really self explanatory for dictionary users
  * There should no longer be empty dialect cases, following 597780d1814acc4c58b060114932a415f589dc1a

I just have #68 on my list, and after that we can release as far as I am concerned. Thanks everyone and let me know if you still have other concerns.

**Comment by dwerning** [comment]
> I decided to put the Coptic lemma not in brackets, but in a new line

Now the citation string is not o.k. anymore (remember it is and should be the same as the heading). I suggest to take this change back,

> adjusted the headers

Since you decided not to add the Lemma section, please put the "form" back into "TLA form ID". Otherwise it is confusing as we discussed at length in another thread.

> removed the heading 'senses'

Indeed, I now find it disturbing that often there is a paragraph beginning with "1." (looking like the letter "l.") without "2.". With the heading it looked like a list, now it is confusing IMO.

**Comment by amir-zeldes** [comment]
Ugh, sorry about the citation, that was an oversight. The citation is back the way it was now.

The 'TLA form ID' header is too long for mobile and will result in wrapping. I think since the table says 'form' it is understood that "ID" means "ID for this form", and the citation box says exactly how to cite anyway.

As for the senses, I can remove '1.' if there is only one sense, but I think we shouldn't have a heading 'senses' only sometimes. Ultimately it's inevitable that there will be different aesthetic opinions, so if the above idea is OK I will implement it, and if not I think both are fine really.

**Comment by ctschroeder** [comment]
Hi!  I checked a couple of different entries on mobile, and it looks good to me! Thanks for everyone's flexibility.  Thank you also @amir-zeldes for adjusting the icons; I was getting feedback that people didn't understand the ANNIS logo but that they do understand the C logo.  I am happy with the current state of things.

I also have no objections to deploying to the main server/domain.  I know people will be very excited for the new version!

**Comment by amir-zeldes** [comment]
Thanks @ctschroeder - let me know what you all think still needs to be done for 2.0.0. I think there are definitely some more improvements we can work towards, but that this is a good point to make a release and let some external users start giving feedback as well.

**Comment by phoenix-mossimo** [comment]
- Two lines in the title ain't no good to me - I am for "TLA lemma no. C8719 : ⲇⲉ" in one line ( removing "Entry"). 
- I would try with lemma table as suggested by @dwerning , especially since we can try functional division between Annis search starting with lemma / non-lemma forms.
- Removal of the title "Senses" is OK.

**Comment by amir-zeldes** [comment]
@phoenix-mossimo could you explain your rationale for preferring lemma IDs on one line *before* the actual Coptic?

I think 99% of users don't care what the ID is, and if they need to cite the entry, there is a dedicated box explaining how to do so. IMO the main purpose of the heading is to verify that the user is on the page they think they are, so having to notice that it's at the end of the line after an arbitrary ID is more cognitively taxing. If you really don't like two lines that's an aesthetic consideration I can understand (wastes vertical space too), but is there a reason for putting the Coptic words last?

**Comment by phoenix-mossimo** [comment]
Is everyone here liking two-line entry title? If yes, as a true Belarusian loving democratic decisions, I will accept the opinion of the majority.

**Comment by ctschroeder** [comment]
I’m not sure what we mean by democracy here—if voting by individuals or by project and who gets a vote. More important to me is the goal of the page header and how we are achieving that goal. One voice can be persuasive. 

I prefer a user-oriented approach: either the lemma is first with one line or use two lines so the lemma is easily spotted in the left margin by the user. I suggested two lines because I thought it was important to the TLA to have the TLA id beginning a line. 

My concern is purely for making the page easy to navigate for the user and I have not seen an explanation as to why putting the entry at the end of a line is easier for the user :) :) :). So my vote is lemma on the left, whether one or two lines. 

Sent from my iPhone

>

**Comment by KaJohn-DDGLC** [comment]
On the level of the user interface, both in printed and online dictionaries, the headword is the most important string to recognize the entry for a human reader. Since the headword is currently in second position, having a line break makes it more accessible. But if I could choose, I would put everything in one line: lemma string first, ID string second. The later one preferably even in a different formatting, e.g. in parenthesis and/or gray, that would make it consistent with how forms and their IDs are presented. It is also consistent with the Online TLA where lemma string and ID are shown that way http://aaew.bbaw.de/tla/servlet/GetWcnDetails?u=guest&f=0&l=0&wn=550034&db=0 which is very typical for online dictionaries that actually show the ID (some provide a button in front or after the lemma that provides the ID and how to cite the entry).

**Comment by amir-zeldes** [comment]
I agree with @KaJohn-DDGLC - and I personally don't mind if it's one line or two, as long as it's easy to see what the entry title is. I've played around with it and I think gray looks washed out against the blue background - how about dark blue? I have some examples here, but the issue with the one line solution is that it wraps in a bad place on mobile:

![image](https://user-images.githubusercontent.com/2188635/59516201-cef25900-8e8e-11e9-800c-631dd61d9071.png)

On desktop it looks fine:

![image](https://user-images.githubusercontent.com/2188635/59516240-e598b000-8e8e-11e9-852b-c0f1efa55e95.png)

This is mobile with the line break:

![image](https://user-images.githubusercontent.com/2188635/59516390-40320c00-8e8f-11e9-8f46-2535323b587d.png)

Let me know what you think - I would like to choose one and move ahead with the release if possible!

**Comment by ctschroeder** [comment]
I also agree with @KaJohn-DDGLC on design I am ok with the line breaking on mobile. (My concern about mobile before was the grid lineup for the entries.)  So either option works for me.

**Comment by phoenix-mossimo** [comment]
I am OK with no 3.

**Comment by amir-zeldes** [comment]
OK, I did 3, without the brackets, and in dark gray based on feedback that blue makes it look like a link. If this is OK, can we declare milestone 2.0.0 complete and release?

**Comment by dwerning** [comment]
Dear all,
My inital argument from #61 quoted above for a sequence "TLA lemma no. C6507 (ϩⲙϩⲁⲗ)" was 
- that there are many entries "ϩⲙϩⲁⲗ" but only one entry "lemma no. C6507". Therefore, from a citation perspective, it makes sense to tahe the ID as the first/central part (without brackets) and the Coptic string as secondary (in brackets or after ":").
- I (tacitly) took and take it that the citation string should be _identical_ to the page title.
- Consequently, the sequences "TLA lemma no. C6507 (ϩⲙϩⲁⲗ)", "TLA lemma no. C6507: ϩⲙϩⲁⲗ" or with line break "TLA lemma no. C6507 < br/ >ϩⲙϩⲁⲗ" make sense to me. (@KaJohn-DDGLC note that in TLA there is an _unambigous_ hieroglyphic string at the beginning, which is not the case for Coptic homophones/nyms, e.g., ϩⲙϩⲁⲗ).  

This is the citation-ist perspective.
I understand, however, the concerns to put the Coptic string in one line after the ID. As a **compromise between both concerns**, I suggest the sequence:
"TLA lemma no. C6507
ϩⲙϩⲁⲗ" 
in the title (which moves "ϩⲙϩⲁⲗ" even closer to the content box; colors as they are, i.e., ID greyish, lemma black) and 
"TLA lemma no. C6507: ϩⲙϩⲁⲗ" with ":"
in the citation string.

**Comment by dwerning** [comment]
forgot to insist: Since you decided not to add the Lemma section, please put the "form" back into "TLA form ID".


-------- Ursprüngliche Nachricht --------
Von: Amir Zeldes
Datum:11.06.2019 22:08 (GMT+01:00)
An: KELLIA/dictionary
Cc: "Werning, Daniel" ,Comment
Betreff: Re: [KELLIA/dictionary] CDO entry page design in mobile (#67)


Ugh, sorry about the citation, that was an oversight. The citation is back the way it was now.

The 'TLA form ID' header is too long for mobile and will result in wrapping. I think since the table says 'form' it is understood that "ID" means "ID for this form", and the citation box says exactly how to cite anyway.

As for the senses, I can remove '1.' if there is only one sense, but I think we shouldn't have a heading 'senses' only sometimes. Ultimately it's inevitable that there will be different aesthetic opinions, so if the above idea is OK I will implement it, and if not I think both are fine really.

**Comment by ctschroeder** [comment]
Hi! So if I am understanding correctly, Katrin, Maxim, Amir, and Carrie all consent to #3 and we have a version of that now installed on the test site (without parentheses, dark grey instead of blue). @dwerning can you take one for the team here and agree to release? I think the design reflects the input from everyone even though it is not exactly the way each person would wish. Thanks!

**Comment by dwerning** [comment]
Dear @ctschroeder,  
wasn't it you raised the doubt in a reply to @phoenix-mossimo that this is about democracy.
>  I’m not sure what we mean by democracy here—if voting by individuals or by project and who gets a vote. ... One voice can be persuasive.

Anyhow, the pick of # 3 by individuals didn't include the version as a 'choice' that I advocated -- so one cannot take it as a vote against it. (Indeed among my suggestions was the version that everyone who took part in the discussion back then agreed on a while ago before the issue with the line break was brought up.)
I still believe in what I said. So in the end it indeed needs to be a 'vote', I guess for eigther

(A)
_Title_
  "**ϩⲙϩⲁⲗ**
   TLA lemma no. C6507"
_Citation_
  "ϩⲙϩⲁⲗ: TLA lemma no. C6507"

OR

(B)
_Title_
  "TLA lemma no. C6507
   **ϩⲙϩⲁⲗ**"
_Citation_
  "TLA lemma no. C6507: ϩⲙϩⲁⲗ"

(but not a mixture of the sequences).
And my vote is B.

**Comment by dwerning** [comment]
(and: please remember the "TLA form ID" heading ... that is not a simple design issue for us.)

**Comment by phoenix-mossimo** [comment]
I still don't like two lines and think we would eventually need a professional clean up the UI. But for now I find the argument that TLA ID placed first eliminates possible ambiguity convincing and vote for B.

**Comment by KaJohn-DDGLC** [comment]
I vote for B because I want to go ahead.

> I still don't like two lines and think we would eventually need a professional clean up the UI. 

I agree with your perception about the two lines and your suggestion to have a 'clean up' of the UI, eventually. But it is clear that the mobile version will have two lines as a user experience. Maybe it would be possible to treat both device types 'differently' (in a later version): one line as the standard, but a properly wrapped two line treatment for mobile devices.

> But for now I find the argument that TLA ID placed first eliminates possible ambiguity convincing and vote for B. 
It is not the placement of the ID that eliminates the possible ambiguity, it is the 'composition' of both of them (as you would have it with composite keys in DB design). In the end, the ID serves here (besides other aspects) as a homonym/homograph marker. If this type of marker is just an index number, it makes not much of a difference for the user/reader if it is placed before or after. For a long string as in our case, it probably makes a difference for the user. As @ctschroeder pointed out 'I prefer a user-oriented approach' and so do I. The user knows best. Let's see if and what feedback we will get about the position of headword and ID.

**Comment by dwerning** [comment]
@amir-zeldes, I am o.k. with your suggestion to write "**Form ID**" in the header to save space. (As a lexicographical project it is important to us to be clear about whether we are talking about the lemma label(-form) or just an particular form of a lemma.) **Please do so.** 
BTW, the form IDs are also important to us since they will host the links to TLA as soon as Coptic data in the TLA exist.

**Comment by amir-zeldes** [comment]
Done
