### ISSUE TITLE
Display entries belonging to “superentry” in the first “search results” window

### ISSUE THREAD

**Issue by phoenix-mossimo** [KELLIA/dictionary#7]
Examples: 

Search for "ⲉⲓⲣⲉ": In the first "search results" window we get ex. "ⲣ ⲁⲥ" ("become old"), but not ex. "ⲉⲓⲣⲉ (ⲉ-)" ("attack"), although it's "ⲉⲓⲣⲉ (ⲉ-)" which is grouped semantically together with "ⲉⲓⲣⲉ" by Crum and belongs to the same superentry in our XML. 

The same applies for ex. to "ⲙⲁ", where "ⲙⲁ ⲛⲧⲡⲉ" ("upper part of the house") is displayed, but "ⲡⲉⲓⲙⲁ" ("this world") or "ϯ ⲙⲁ" ("give place") are not displayed in the first search results window, although in the same entry of Crum. 

Forms like these are grouped in “See also” section of a relevant entry, which might also be not so easy to find (see #1 and #2).  My point is that the information contained in the superentry is more relevant for the user and could be immediately availble in the first search results window. 

Additional difficulty is that forms like “ⲉⲓⲣⲉ (ⲉ-)” cannot be found through the search bar as they contain brackets reserved for rexeg.

**Comment by amir-zeldes** [comment]
I've had a look at this: I'm not entirely sure what you would like here, since the items in question are not in the first entry of the super-entry in the original XML. So, for example, if you are searching for 'ma', you will get the first six readings which are part of subentry 1 - from 1. place through 6. part, duty. 

For the display of related additional subentries, we agreed to only show the first one if available, for space reasons. If we decide to include pei-ma, how do we know where to stop? pei-ma is entry number 2, but there is a total of 9(!) entries under the 'ma' super entry, of which the first already has 6 sub-senses. Including all of these on the first results page, which already has 27 separate super-entries for ma (not found under ma), would make that view much less usable in my opinion. 

It's possible that for 'ma' the reading 'world' is very important, and should be in the first entries sense-list, but in the general case, the results page is meant for you to identify 'I mean the one with places, not 'give' or 'if', and then you can see more under details. The trick is to make decisions that are applicable to all entries, and this is sadly not so easy... 

Let me know if you can think of a good algorithm for what you'd like to see, otherwise I'll probably close this as wontfix.

**Comment by phoenix-mossimo** [comment]
I agree - "wontfix" is good as long as #1 and #2 are resolved.
