### ISSUE TITLE
Unhandled errors when searchin for *\s

### ISSUE THREAD

**Issue by ailintom** [KELLIA/dictionary#74]
Dear KELLIA team,

many thanks for the excellent tool and for making the source code available online. I was playing around with some regular expressions (trying to figure out how you combine some end-user-software style regexes (*) with full-fledged regular expressions (you reference to https://www.regular-expressions.info/ in yout manual) and I found out that  search queries starting with *\ produce unhandled errors in your website. Examples: 

https://coptic-dictionary.org/results.cgi?quick_search=*%5Cs
https://coptic-dictionary.org/results.cgi?quick_search=*%5Cs*

Thanks
Alexander Ilin-Tomich

**Comment by phoenix-mossimo** [comment]
Dear Alexander, thank you for your report. You are right - we need a graceful response to the unhandled exceptions, such as invalid regex `*\s,` where the token preceding `*` is not quantifiable. 

In that case a user-friendly error page should be displayed.

@amir-zeldes - what do you think?

**Comment by amir-zeldes** [comment]
Thanks for reporting this - `*\s` is indeed an invalid regular expression and the interface should catch that and not attempt regex search. I've fixed it now, so that if the search expression is invalid, the interface will search for the literal expression instead - in the case of your query, this produces zero results but no crash.
