### ISSUE TITLE
ⲡⲟⲟⲩ (ⲡϩⲟⲟⲩ) even more confusing

### ISSUE THREAD

**Issue by m-linssen** [KELLIA/dictionary#94]
https://coptic-dictionary.org/entry.cgi?tla=C6968 is the entry for the word today: ⲡⲟⲟⲩ.
It points to Crum 731 http://coptot.manuscriptroom.com/crum-coptic-dictionary/?docID=800000&pageID=731

where it says: ⲡⲟⲟⲩ (for ⲡϩⲟⲟⲩ)

Thus far, the usual use of brackets in KELLIA, going by the 6,000 (non unique) lemmas I've seen thus far, is exemplified below:

ⲛⲏⲩ (ⲉϩⲟⲩⲛ)
ⲉⲓⲛⲉ (ⲛ-, ⲙⲙⲟ⸗)
ⲛⲁ(ⲉ)ⲓⲁⲧ⸗
ϭ(ⲉ)ⲗⲙⲁⲓ
ϩⲟ(ⲉ)ⲓⲛⲉ

where the brackets indicate "followed by" (the first two examples) or "either with or without".
That is confusing enough as it is: the first two cases would be clear if they'd be described as follows:

ⲛⲏⲩ ⲉϩⲟⲩⲛ
ⲉⲓⲛⲉ [ⲛ-, ⲙⲙⲟ⸗]

so that round brackets are reserved for variants. The above two clearly don't denote optionality, but a prerequisite; in the latter case you have a choice between two forms of a prerequisite, but the prerequisite is there regardless of either form

If you don't use a notation like that, then all the different forms of ⲛⲏⲩ become meaningless:

ⲛⲏⲩ (ⲛⲥⲁ-)
ⲛⲏⲩ (ⲙⲛⲛⲥⲁ-)
ⲛⲏⲩ (ϣⲁ-)
ⲛⲏⲩ (ϩⲁ-)
ⲛⲏⲩ (ⲉⲃⲟⲗ)
ⲛⲏⲩ (ⲉⲡⲉⲥⲏⲧ)
ⲛⲏⲩ (ⲉⲡϣⲱⲓ)

These forms of ⲛⲏⲩ all come with a different second lemma - not with an optional one

Regarding the second set of examples, those clearly indicate optionality; the words can have the additional letter or not:

ⲛⲁ(ⲉ)ⲓⲁⲧ⸗
ϭ(ⲉ)ⲗⲙⲁⲓ
ϩⲟ(ⲉ)ⲓⲛⲉ

Now, in the title to this issue there is an even more confusing use of round brackets, and a fairly useless one if I may say so: it's an etymological pointer, and says "ⲡⲟⲟⲩ is derived from ⲡϩⲟⲟⲩ".
It does not indicate optionality, where for instance ⲡⲟⲟⲩ ⲡϩⲟⲟⲩ would be legit and mean the same as ⲡⲟⲟⲩ.
Nor does it indicate that ⲡⲟⲟⲩ only means ... when followed by ⲡϩⲟⲟⲩ

Can you please fix entries like these? All of these?

I realise I'm criticising not only the userfriendliness of your dictionary, but am increasingly objecting to its consistency, general design and architecture.
And I am indeed, but that doesn't mean I am not very happy with KELLIA. I am very happy with KELLIA, very very happy. But there's a but, and it's getting bigger by the day

I know nothing of Coptic, at least hadn't even read any before September. Nor am I a profesional linguist in any way. I do have a degree and am more or less fluent in a handful Indo European languages, but basically all of that is nothing more than a hobby.
Yet I do know about organisation, consistency, architecture, and design. And as a user of KELLIA, an increasing amount of that is lacking. It helps, or doesn't help, that I'm a complete n00b in Coptic, perhaps, and maybe I'm not the target audience, or at least not the intended audience. But I do know how to read and use a dictionary - and I find myself beyond the point of adapting to the enormous variation in annotation.

**Comment by amir-zeldes** [comment]
Related: #30

**Comment by phoenix-mossimo** [comment]
@m-linssen The observations you make are extremely useful and helpful. Consistency is a problem, considering that initially more than 10 people worked on the compilation of the dictionary without a proper XML Schema. Tons of issues were resolved already, even before the first version was released, but some are left. Therefore all your remarks are valuable and are highly appreciated.

Considering the varying semantics of the brackets - the issue is known and has been resolved according to the description in https://github.com/KELLIA/dictionary/wiki/A0:-Project:-Remove-brackets-from-orthographic-variants (but not released yet). The case of ⲡⲟⲟⲩ (ⲡϩⲟⲟⲩ) is handled in A2.2: https://github.com/KELLIA/dictionary/wiki/A2.2.-Bracket-NOT-at-word-beginning-and-preceded-by-white-space. You can take a look and leave comments here, in #30 or in the project documentation itself.

**Comment by phoenix-mossimo** [comment]
Parenthesis-problem resolved according to the description in  https://github.com/KELLIA/dictionary/wiki/A0:-Project:-Remove-brackets-from-orthographic-variants. The remaining forms , containing parenthesis, all denote collocated prepositions / adverbs: https://github.com/KELLIA/dictionary/wiki/A3:-The-remaining-forms-containing-brackets., which is in line with TLA notation: e.g. http://aaew.bbaw.de/tla/servlet/GetWcnDetails?u=guest&f=0&l=0&wn=855910&db=0
